name: Destroy

on:
  pull_request:
    types: [ closed ]
    branches-ignore: [ development, master ]

jobs:
  destroy:
    name: Destroy old feature service
    runs-on: ubuntu-latest
    steps:
      - uses: FranzDiebold/github-env-vars-action@v1.0.0

      - name: Checkout the repository
        uses: actions/checkout@v1

      - name: Authenticate into Google Cloud Platform
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_email: beng-477@recharge-adapter.iam.gserviceaccount.com
          service_account_key: ${{ secrets.GCLOUD_AUTH }}

      - name: Destroy
        run: gcloud run services delete recharge-feature-$GITHUB_REF_NAME --quiet --project recharge-adapter --region us-east1 --platform managed
